library("DelayedArray")
library("HDF5Array")
library("BiocSingular")
library("testthat")
library("rTensor")
library("DelayedRandomArray")
library("einsum")
library("DelayedTensor")

options(testthat.use_colours = FALSE)

source("../R/Decomp.R")
source("../R/Einsum.R")
source("../R/Generics.R")
source("../R/Global-settings.R")
source("../R/Misc.R")
source("../R/SVD.R")
source("../R/Utils.R")
source("../R/zzz.R")

for(size in c(1E+9,1E+8,1E+7,1E+6,1E+5,1E+4,1E+3,1E+2,50,20:1)){
    setAutoBlockSize(size=size)
    getAutoBlockSize()
    # source → test_file
    # source("testthat/test_Generics.R")
    # source("testthat/test_Misc.R")
    # source("testthat/test_SVD.R")
    # source("testthat/test_Decomp.R")
    # source("testthat/test_4thorder.R")
    # source("testthat/test_Einsum_objects.R")
    # source("testthat/test_Einsum.R")
    # gc();gc()
}
setAutoBlockSize(size=1E+8)
source("testthat/test_Verbose.R")
source("testthat/test_Sparse.R")
