library("DelayedArray")
library("HDF5Array")
library("BiocSingular")
library("testthat")
library("rTensor")
library("DelayedRandomArray")
library("einsum")

options(testthat.use_colours = FALSE)

# rm
source("../R/Utils.R")
source("../R/Array.R")
source("../R/AllGenerics.R")
source("../R/Misc.R")
source("../R/SVD.R")
source("../R/Decomp.R")
# source("../R/Einsum.R")

for(size in c(100000,10000,1000,100,50,20:1)){
	setAutoBlockSize(size=size)
	getAutoBlockSize()
	# source -> test_file
	print("Array")
	source("testthat/test_Array.R")
	print("AllGenerics")
	source("testthat/test_AllGenerics.R")
	print("Misc")
	source("testthat/test_Misc.R")
	print("SVD")
	source("testthat/test_SVD.R")
	print("Decomp")
	source("testthat/test_Decomp.R")
	print("4thorder")
	source("testthat/test_4thorder.R")
	# print("Einsum_objects")
	# source("testthat/test_Einsum_objects.R")
	# print("Einsum")
	# source("testthat/test_Einsum.R")
}
setAutoBlockSize(size=1e8)
