darr_human_mini <- DelayedArray(as.array(human_mid_brain[1:10, 1:10]))
darr_mouse_mini <- DelayedArray(as.array(mouse_mid_brain[1:10, 1:10]))

setVerbose(TRUE)
setAutoBlockSize(size=1E+8)

# einsum
# .block_einsum/einsum::einsum (52.50%)
# write_block (63.28%)
print("einsum")
setSparse(FALSE)
Rprof()
try(darr <- einsum('ij,ik->ijk', darr_human_mini, darr_mouse_mini))
Rprof(NULL)
prof_einsum <- summaryRprof()
save(prof_einsum, file="prof_einsum.RData")

# vec (Dense)
# writeHDF5Array (99.68%)
print("vec (Dense)")
setSparse(FALSE)
Rprof()
try(vec(darr))
Rprof(NULL)
prof_vec_dense <- summaryRprof()
save(prof_vec_dense, file="prof_vec_dense.RData")

# vec (Sparse)
# dense2sparse (87.19%)
# SparseArraySeed (43.26%)
print("vec (Sparse)")
setSparse(TRUE)
Rprof()
try(v <- vec(darr))
Rprof(NULL)
prof_vec_sparse <- summaryRprof()
save(prof_vec_sparse, file="prof_vec_sparse.RData")

# .reshapeIncNumbers1D
# XXXXXX (XX.XX%)
print(".reshapeIncNumbers1D")
Rprof()
try(DelayedTensor:::.reshapeIncNumbers1D(v, as.integer(prod(dim(darr)))))
Rprof(NULL)
prof_reshape1D_dense <- summaryRprof()
save(prof_reshape1D_dense, file="prof_reshape1D_dense.RData")

# .reshapeIncNumbers1DSparse
# read_block (84.49%)
print(".reshapeIncNumbers1DSparse")
Rprof()
try(DelayedTensor:::.reshapeIncNumbers1DSparse(v, as.integer(prod(dim(darr)))))
Rprof(NULL)
prof_reshape1D_sparse <- summaryRprof()
save(prof_reshape1D_sparse, file="prof_reshape1D_sparse.RData")

# unfold (Dense)
# h5write/write_block (85.53%)
# vec (44.11%)
print("unfold (Dense)")
setSparse(FALSE)
Rprof()
try(dmat <- unfold(darr, row_idx=1:2, col_idx=3))
Rprof(NULL)
prof_unfold_dense <- summaryRprof()
save(prof_unfold_dense, file="prof_unfold_dense.RData")

# unfold (Sparse)
# read_block (57.20%)
# extract_sparse_array (23.54%)
print("unfold (Sparse)")
setSparse(TRUE)
Rprof()
try(unfold(darr, row_idx=1:2, col_idx=3))
Rprof(NULL)
prof_unfold_sparse <- summaryRprof()
save(prof_unfold_sparse, file="prof_unfold_sparse.RData")

# modeSum (Dense)
# realize/writeHDF5Array (57.56%)
# read_block (31.90%)
print("modeSum (Dense)")
setSparse(FALSE)
Rprof()
try(modeSum(darr, m=2))
Rprof(NULL)
prof_modesum_dense <- summaryRprof()
save(prof_modesum_dense, file="prof_modesum_dense.RData")

# modeSum (Sparse)
# which (81.42%) <- 改善できそう?
print("modeSum (Sparse)")
Rprof()
try(modeSum(darr, m=2))
Rprof(NULL)
prof_modesum_sparse <- summaryRprof()
save(prof_modesum_sparse, file="prof_modesum_sparse.RData")

# innerProd (Dense)
# sum (100.0%)
print("innerProd (Dense)")
setSparse(FALSE)
Rprof()
try(innerProd(darr, darr))
Rprof(NULL)
prof_innerprod_dense <- summaryRprof()
save(prof_innerprod_dense, file="prof_innerprod_dense.RData")

# innerProd (Sparse)
# XXXXXX (XX.XX%)
print("innerProd (Sparse)")
setSparse(TRUE)
Rprof()
try(innerProd(darr, darr))
Rprof(NULL)
prof_innerprod_sparse <- summaryRprof()
save(prof_innerprod_sparse, file="prof_innerprod_sparse.RData")

# hadamard (Dense)
# XXXXXX (XX.XX%)
print("hadamard (Dense)")
setSparse(FALSE)
Rprof()
try(hadamard(darr, darr))
Rprof(NULL)
prof_hadamard_dense <- summaryRprof()
save(prof_hadamard_dense, file="prof_hadamard_dense.RData")

# hadamard (Sparse)
# XXXXXX (XX.XX%)
print("hadamard (Sparse)")
setSparse(TRUE)
Rprof()
try(hadamard(darr, darr))
Rprof(NULL)
prof_hadamard_sparse <- summaryRprof()
save(prof_hadamard_sparse, file="prof_hadamard_sparse.RData")

# kronecker (Dense)
# XXXXXX (XX.XX%)
print("kronecker (Dense)")
setSparse(FALSE)
Rprof()
try(kronecker(darr, darr))
Rprof(NULL)
prof_hronecker_dense <- summaryRprof()
save(prof_hronecker_dense, file="prof_hronecker_dense.RData")

# kronecker (Sparse)
# XXXXXX (XX.XX%)
print("kronecker (Sparse)")
setSparse(TRUE)
Rprof()
try(kronecker(darr, darr))
Rprof(NULL)
prof_hronecker_sparse <- summaryRprof()
save(prof_hronecker_sparse, file="prof_hronecker_sparse.RData")

# khatri_rao (Dense)
# XXXXXX (XX.XX%)
print("khatri_rao (Dense)")
setSparse(FALSE)
Rprof()
try(khatri_rao(darr[,,1], darr[,,1]))
Rprof(NULL)
prof_khatri_rao_dense <- summaryRprof()
save(prof_khatri_rao_dense, file="prof_khatri_rao_dense.RData")

# khatri_rao (Sparse)
# XXXXXX (XX.XX%)
print("khatri_rao (Sparse)")
setSparse(TRUE)
Rprof()
try(khatri_rao(darr[,,1], darr[,,1]))
Rprof(NULL)
prof_khatri_rao_sparse <- summaryRprof()
save(prof_khatri_rao_sparse, file="prof_khatri_rao_sparse.RData")

# fold (Dense)
# XXXXXX (XX.XX%)
print("fold (Dense)")
setSparse(FALSE)
Rprof()
try(fold(dmat, row_idx=1:2, col_idx=3, dim(darr)))
Rprof(NULL)
prof_fold_dense <- summaryRprof()
save(prof_fold_dense, file="prof_fold_dense.RData")

# fold (Sparse)
# XXXXXX (XX.XX%)
print("fold (Sparse)")
setSparse(TRUE)
Rprof()
try(fold(dmat, row_idx=1:2, col_idx=3, dim(darr)))
Rprof(NULL)
prof_fold_sparse <- summaryRprof()
save(prof_fold_sparse, file="prof_fold_sparse.RData")

# diag
# XXXXXX (XX.XX%)
print("diag")
Rprof()
try(DelayedTensor::diag(darr))
Rprof(NULL)
prof_diag1 <- summaryRprof()
save(prof_diag1, file="prof_diag1.RData")

# "diag<-"
# writeHDF5Array (99.55%)
print("diag<-")
Rprof()
try(DelayedTensor::diag(darr) <- seq(min(dim(darr))))
Rprof(NULL)
prof_diag2 <- summaryRprof()
save(prof_diag2, file="prof_diag2.RData")

# modebind_list (Dense)
# XXXXXX (XX.XX%)
print("modebind_list (Dense)")
setSparse(FALSE)
Rprof()
try(modebind_list(list(darr, darr), m=1))
Rprof(NULL)
prof_modebind_list_dense <- summaryRprof()
save(prof_modebind_list_dense, file="prof_modebind_list_dense.RData")

# modebind_list (Sparse)
# XXXXXX (XX.XX%)
print("modebind_list (Sparse)")
setSparse(TRUE)
Rprof()
try(modebind_list(list(darr, darr), m=1))
Rprof(NULL)
prof_modebind_list_sparse <- summaryRprof()
save(prof_modebind_list_sparse, file="prof_modebind_list_sparse.RData")

# DelayedDiagonalArray
# as.list (62.50%)
print("DelayedDiagonalArray")
Rprof()
try(DelayedDiagonalArray(c(100,200,300), 1:100))
Rprof(NULL)
prof_delayeddiagonalarray <- summaryRprof()
save(prof_delayeddiagonalarray, file="prof_delayeddiagonalarray.RData")

# hosvd (Dense)
# XXXXXX (XX.XX%)
print("hosvd (Dense)")
setSparse(FALSE)
Rprof()
try(hosvd(darr, ranks=c(2,3,4)))
Rprof(NULL)
prof_hosvd_dense <- summaryRprof()
save(prof_hosvd_dense, file="prof_hosvd_dense.RData")

# hosvd (Sparse)
# XXXXXX (XX.XX%)
print("hosvd (Sparse)")
setSparse(TRUE)
Rprof()
try(hosvd(darr, ranks=c(2,3,4)))
Rprof(NULL)
prof_hosvd_sparse <- summaryRprof()
save(prof_hosvd_sparse, file="prof_hosvd_sparse.RData")

# cp (Dense)
# XXXXXX (XX.XX%)
print("cp (Dense)")
setSparse(FALSE)
Rprof()
try(cp(darr, num_components=3, max_iter=2))
Rprof(NULL)
prof_cp_dense <- summaryRprof()
save(prof_cp_dense, file="prof_cp_dense.RData")

# cp (Sparse)
# こける
# Error in dim(idx) <- c(.ndim(sarr2), length(idx)/.ndim(sarr2)) :
#   dims [product 32] do not match the length of object [33]
# XXXXXX (XX.XX%)
print("cp (Sparse)")
setSparse(TRUE)
Rprof()
try(cp(darr, num_components=3, max_iter=2))
Rprof(NULL)
prof_cp_sparse <- summaryRprof()
save(prof_cp_sparse, file="prof_cp_sparse.RData")

# tucker (Dense)
# XXXXXX (XX.XX%)
print("tucker (Dense)")
setSparse(FALSE)
Rprof()
try(tucker(darr, ranks=c(2,2,2), max_iter=2))
Rprof(NULL)
prof_tucker_dense <- summaryRprof()
save(prof_tucker_dense, file="prof_tucker_dense.RData")

# tucker (Sparse)
# Warning in irlba(smat, k) :
#   You're computing too large a percentage of total singular values, use a standard svd instead.
# Warning in irlba(smat, k) :
#   You're computing too large a percentage of total singular values, use a standard svd instead.
# Warning in irlba(smat, k) :
#   You're computing too large a percentage of total singular values, use a standard svd instead.
# XXXXXX (XX.XX%)
print("tucker (Sparse)")
setSparse(TRUE)
Rprof()
try(tucker(darr, ranks=c(2,2,2), max_iter=2))
Rprof(NULL)
prof_tucker_sparse <- summaryRprof()
save(prof_tucker_sparse, file="prof_tucker_sparse.RData")

# mpca (Dense)
# XXXXXX (XX.XX%)
print("mpca (Dense)")
setSparse(FALSE)
Rprof()
try(mpca(darr, ranks=c(2,2), max_iter=2))
Rprof(NULL)
prof_mpca_dense <- summaryRprof()
save(prof_mpca_dense, file="prof_mpca_dense.RData")

# mpca (Sparse)
# XXXXXX (XX.XX%)
print("mpca (Sparse)")
setSparse(TRUE)
Rprof()
try(mpca(darr, ranks=c(2,2), max_iter=2))
Rprof(NULL)
prof_mpca_sparse <- summaryRprof()
save(prof_mpca_sparse, file="prof_mpca_sparse.RData")

# pvd (Dense)
# XXXXXX (XX.XX%)
# こける
# Error in validObject(.Object) : invalid class “DelayedArray” object:
#     the supplied seed must have dimensions
print("pvd (Dense)")
setSparse(FALSE)
Rprof()
try(pvd(darr, uranks=rep(2, dim(darr)[3]), wranks=rep(3, dim(darr)[3]),
	a=2, b=3))
Rprof(NULL)
prof_pvd_dense <- summaryRprof()
save(prof_pvd_dense, file="prof_pvd_dense.RData")

# pvd (Sparse)
# XXXXXX (XX.XX%)
# こける
# Error in validObject(.Object) : invalid class “DelayedArray” object:
#     the supplied seed must have dimensions
print("pvd (Sparse)")
setSparse(TRUE)
Rprof()
try(pvd(darr, uranks=rep(2, dim(darr)[3]), wranks=rep(3, dim(darr)[3]),
	a=2, b=3))
Rprof(NULL)
prof_pvd_sparse <- summaryRprof()
save(prof_pvd_sparse, file="prof_pvd_sparse.RData")
