# # DelayedArray objects

# context("### einsum (transpose) ###\n")
# expect_equal(as.vector(A), as.vector(einsum('i', A)))
# expect_equal(D, as.array(einsum('ij', D)))
# expect_equal(F, as.array(einsum('ijk', F)))
# expect_equal(G, as.array(einsum('ijkl', G)))
# expect_equal(t(D), as.array(einsum('ji', D)))
# expect_equal(t(D), as.array(einsum('ij->ji', D)))

# expect_equal(aperm(F, c(1,3,2)), as.array(einsum('ikj', F)))
# expect_equal(aperm(F, c(1,3,2)), as.array(einsum('ijk->ikj', F)))
# expect_equal(aperm(F, c(2,1,3)), as.array(einsum('jik', F)))
# expect_equal(aperm(F, c(2,1,3)), as.array(einsum('ijk->jik', F)))
# expect_equal(aperm(F, c(2,3,1)), as.array(einsum('jki', F)))
# expect_equal(aperm(F, c(2,3,1)), as.array(einsum('ijk->jki', F)))
# expect_equal(aperm(F, c(3,1,2)), as.array(einsum('kij', F)))
# expect_equal(aperm(F, c(3,1,2)), as.array(einsum('ijk->kij', F)))
# expect_equal(aperm(F, c(3,2,1)), as.array(einsum('kji', F)))
# expect_equal(aperm(F, c(3,2,1)), as.array(einsum('ijk->kji', F)))
# expect_equal(aperm(G, c(1,2,4,3)), as.array(einsum('ijlk', G)))
# expect_equal(aperm(G, c(1,2,4,3)), as.array(einsum('ijkl->ijlk', G)))
# expect_equal(aperm(G, c(1,3,2,4)), as.array(einsum('ikjl', G)))
# expect_equal(aperm(G, c(1,3,2,4)), as.array(einsum('ijkl->ikjl', G)))
# expect_equal(aperm(G, c(1,3,4,2)), as.array(einsum('iklj', G)))
# expect_equal(aperm(G, c(1,3,4,2)), as.array(einsum('ijkl->iklj', G)))
# expect_equal(aperm(G, c(1,4,2,3)), as.array(einsum('iljk', G)))
# expect_equal(aperm(G, c(1,4,2,3)), as.array(einsum('ijkl->iljk', G)))
# expect_equal(aperm(G, c(1,4,3,2)), as.array(einsum('ilkj', G)))
# expect_equal(aperm(G, c(1,4,3,2)), as.array(einsum('ijkl->ilkj', G)))
# expect_equal(aperm(G, c(2,1,3,4)), as.array(einsum('jikl', G)))
# expect_equal(aperm(G, c(2,1,3,4)), as.array(einsum('ijkl->jikl', G)))
# expect_equal(aperm(G, c(2,1,4,3)), as.array(einsum('jilk', G)))
# expect_equal(aperm(G, c(2,1,4,3)), as.array(einsum('ijkl->jilk', G)))
# expect_equal(aperm(G, c(2,3,1,4)), as.array(einsum('jkil', G)))
# expect_equal(aperm(G, c(2,3,1,4)), as.array(einsum('ijkl->jkil', G)))
# expect_equal(aperm(G, c(2,3,4,1)), as.array(einsum('jkli', G)))
# expect_equal(aperm(G, c(2,3,4,1)), as.array(einsum('ijkl->jkli', G)))
# expect_equal(aperm(G, c(2,4,1,3)), as.array(einsum('jlik', G)))
# expect_equal(aperm(G, c(2,4,1,3)), as.array(einsum('ijkl->jlik', G)))
# expect_equal(aperm(G, c(2,4,3,1)), as.array(einsum('jlki', G)))
# expect_equal(aperm(G, c(2,4,3,1)), as.array(einsum('ijkl->jlki', G)))
# expect_equal(aperm(G, c(3,1,2,4)), as.array(einsum('kijl', G)))
# expect_equal(aperm(G, c(3,1,2,4)), as.array(einsum('ijkl->kijl', G)))
# expect_equal(aperm(G, c(3,1,4,2)), as.array(einsum('kilj', G)))
# expect_equal(aperm(G, c(3,1,4,2)), as.array(einsum('ijkl->kilj', G)))
# expect_equal(aperm(G, c(3,2,1,4)), as.array(einsum('kjil', G)))
# expect_equal(aperm(G, c(3,2,1,4)), as.array(einsum('ijkl->kjil', G)))
# expect_equal(aperm(G, c(3,2,4,1)), as.array(einsum('kjli', G)))
# expect_equal(aperm(G, c(3,2,4,1)), as.array(einsum('ijkl->kjli', G)))
# expect_equal(aperm(G, c(3,4,1,2)), as.array(einsum('klij', G)))
# expect_equal(aperm(G, c(3,4,1,2)), as.array(einsum('ijkl->klij', G)))
# expect_equal(aperm(G, c(3,4,2,1)), as.array(einsum('klji', G)))
# expect_equal(aperm(G, c(3,4,2,1)), as.array(einsum('ijkl->klji', G)))
# expect_equal(aperm(G, c(4,1,2,3)), as.array(einsum('lijk', G)))
# expect_equal(aperm(G, c(4,1,2,3)), as.array(einsum('ijkl->lijk', G)))
# expect_equal(aperm(G, c(4,1,3,2)), as.array(einsum('likj', G)))
# expect_equal(aperm(G, c(4,1,3,2)), as.array(einsum('ijkl->likj', G)))
# expect_equal(aperm(G, c(4,2,1,3)), as.array(einsum('ljik', G)))
# expect_equal(aperm(G, c(4,2,1,3)), as.array(einsum('ijkl->ljik', G)))
# expect_equal(aperm(G, c(4,2,3,1)), as.array(einsum('ljki', G)))
# expect_equal(aperm(G, c(4,2,3,1)), as.array(einsum('ijkl->ljki', G)))
# expect_equal(aperm(G, c(4,3,1,2)), as.array(einsum('lkij', G)))
# expect_equal(aperm(G, c(4,3,1,2)), as.array(einsum('ijkl->lkij', G)))
# expect_equal(aperm(G, c(4,3,2,1)), as.array(einsum('lkji', G)))
# expect_equal(aperm(G, c(4,3,2,1)), as.array(einsum('ijkl->lkji', G)))

# context("### einsum (sum + permutation) ###\n")
# expect_equal(sum(A), as.vector(einsum('i->', A)))
# expect_equal(sum(D), as.vector(einsum('ij->', D)))

# expect_equal(rowSums(D), as.vector(einsum('ij->i', D)))
# expect_equal(colSums(D), as.vector(einsum('ij->j', D)))

# expect_equal(sum(F), as.vector(einsum('ijk->', F)))
# expect_equal(tmp1, as.vector(einsum('ijk->i', F)))
# expect_equal(tmp2, as.vector(einsum('ijk->j', F)))
# expect_equal(tmp3, as.vector(einsum('ijk->k', F)))
# expect_equal(tmp4, as.array(einsum('ijk->ij', F)))
# expect_equal(tmp5, as.array(einsum('ijk->jk', F)))
# expect_equal(tmp6, as.array(einsum('ijk->ik', F)))
# expect_equal(sum(G), as.vector(einsum('ijkl->', G)))
# expect_equal(tmp7, as.vector(einsum('ijkl->i', G)))
# expect_equal(tmp8, as.vector(einsum('ijkl->j', G)))
# expect_equal(tmp9, as.vector(einsum('ijkl->k', G)))
# expect_equal(tmp10, as.vector(einsum('ijkl->l', G)))
# expect_equal(tmp11, as.array(einsum('ijkl->ij', G)))
# expect_equal(tmp12, as.array(einsum('ijkl->ik', G)))
# expect_equal(tmp13, as.array(einsum('ijkl->il', G)))
# expect_equal(tmp14, as.array(einsum('ijkl->ji', G)))
# expect_equal(tmp15, as.array(einsum('ijkl->jk', G)))
# expect_equal(tmp16, as.array(einsum('ijkl->jl', G)))
# expect_equal(tmp17, as.array(einsum('ijkl->ki', G)))
# expect_equal(tmp18, as.array(einsum('ijkl->kj', G)))
# expect_equal(tmp19, as.array(einsum('ijkl->kl', G)))
# expect_equal(tmp20, as.array(einsum('ijkl->li', G)))
# expect_equal(tmp21, as.array(einsum('ijkl->lj', G)))
# expect_equal(tmp22, as.array(einsum('ijkl->lk', G)))
# expect_equal(tmp23, as.array(einsum('ijkl->ijk', G)))
# expect_equal(tmp24, as.array(einsum('ijkl->ijl', G)))
# expect_equal(tmp25, as.array(einsum('ijkl->ikj', G)))
# expect_equal(tmp26, as.array(einsum('ijkl->ikl', G)))
# expect_equal(tmp27, as.array(einsum('ijkl->ilj', G)))
# expect_equal(tmp28, as.array(einsum('ijkl->ilk', G)))
# expect_equal(tmp29, as.array(einsum('ijkl->jik', G)))
# expect_equal(tmp30, as.array(einsum('ijkl->jil', G)))
# expect_equal(tmp31, as.array(einsum('ijkl->jki', G)))
# expect_equal(tmp32, as.array(einsum('ijkl->jkl', G)))
# expect_equal(tmp33, as.array(einsum('ijkl->jli', G)))
# expect_equal(tmp34, as.array(einsum('ijkl->jlk', G)))
# expect_equal(tmp35, as.array(einsum('ijkl->kij', G)))
# expect_equal(tmp36, as.array(einsum('ijkl->kil', G)))
# expect_equal(tmp37, as.array(einsum('ijkl->kji', G)))
# expect_equal(tmp38, as.array(einsum('ijkl->kjl', G)))
# expect_equal(tmp39, as.array(einsum('ijkl->kli', G)))
# expect_equal(tmp40, as.array(einsum('ijkl->klj', G)))
# expect_equal(tmp41, as.array(einsum('ijkl->lij', G)))
# expect_equal(tmp42, as.array(einsum('ijkl->lik', G)))
# expect_equal(tmp43, as.array(einsum('ijkl->lji', G)))
# expect_equal(tmp44, as.array(einsum('ijkl->ljk', G)))
# expect_equal(tmp45, as.array(einsum('ijkl->lki', G)))
# expect_equal(tmp46, as.array(einsum('ijkl->lkj', G)))

# context("### einsum (multiply, diagonal) ###\n")
# expect_equal(diag(C), as.vector(einsum('ii->i', C)))
# expect_equal(tmp47, as.vector(einsum('iii->i', E)))
# expect_equal(tmp48, as.vector(einsum('iiii->i', G)))

# context("### einsum (sum + multiply + transpose) ###\n")
# # Hadamard matrix
# expect_equal(A*A, as.array(einsum('i,i->i', A, A)))
# expect_equal(D*D, as.array(einsum('ij,ij->ij', D, D)))
# expect_equal(F*F, as.array(einsum('ijk,ijk->ijk', F, F)))
# expect_equal(G*G, as.array(einsum('ijkl,ijkl->ijkl', G, G)))

# # Frobenius norm^2
# expect_equal(sum(A*A), as.vector(einsum('i,i', A, A)))
# expect_equal(sum(A*A), as.vector(einsum('i,i->', A, A)))
# expect_equal(sum(D*D), as.vector(einsum('ij,ij', D, D)))
# expect_equal(sum(D*D), as.vector(einsum('ij,ij->', D, D)))
# expect_equal(sum(F*F), as.vector(einsum('ijk,ijk', F, F)))
# expect_equal(sum(F*F), as.vector(einsum('ijk,ijk->', F, F)))
# expect_equal(sum(G*G), as.vector(einsum('ijkl,ijkl', G, G)))
# expect_equal(sum(G*G), as.vector(einsum('ijkl,ijkl->', G, G)))

# expect_equal(sum(C%*%D), as.vector(einsum('ij,jk->', C, D)))

# expect_equal(rowSums(C%*%D), as.vector(einsum('ij,jk->i', C, D)))
# expect_equal(tmp49, as.vector(einsum('ij,jk->j', C, D)))
# expect_equal(colSums(C%*%D), as.vector(einsum('ij,jk->k', C, D)))

# expect_equal(tmp50, as.array(einsum('ij,jk->ij', C, D)))
# expect_equal(tmp51, as.array(einsum('ij,jk->ji', C, D)))
# expect_equal(tmp52, as.array(einsum('ij,jk->jk', C, D)))
# expect_equal(tmp53, as.array(einsum('ij,jk->kj', C, D)))
# expect_equal(tmp54, as.array(einsum('ij,jk->ik', C, D)))
# expect_equal(tmp55, as.array(einsum('ij,jk->ki', C, D)))

# expect_equal(tmp56, as.array(einsum('ij,jk->ijk', C, D)))
# expect_equal(tmp57, as.array(einsum('ij,jk->ikj', C, D)))
# expect_equal(tmp58, as.array(einsum('ij,jk->jik', C, D)))
# expect_equal(tmp59, as.array(einsum('ij,jk->jki', C, D)))
# expect_equal(tmp60, as.array(einsum('ij,jk->kij', C, D)))
# expect_equal(tmp61, as.array(einsum('ij,jk->kji', C, D)))

# expect_equal(tmp62, as.vector(einsum('ij,ijk->', C, E)))
# expect_equal(tmp63, as.vector(einsum('ij,ijk->i', C, E)))
# expect_equal(tmp64, as.vector(einsum('ij,ijk->j', C, E)))
# expect_equal(tmp65, as.vector(einsum('ij,ijk->k', C, E)))
# expect_equal(tmp66, as.array(einsum('ij,ijk->ij', C, E)))
# expect_equal(tmp67, as.array(einsum('ij,ijk->ji', C, E)))
# expect_equal(tmp68, as.array(einsum('ij,ijk->jk', C, E)))
# expect_equal(tmp69, as.array(einsum('ij,ijk->kj', C, E)))
# expect_equal(tmp70, as.array(einsum('ij,ijk->ik', C, E)))
# expect_equal(tmp71, as.array(einsum('ij,ijk->ki', C, E)))
# expect_equal(tmp72, as.array(einsum('ij,ijk->ijk', C, E)))

# expect_equal(tmp73, as.vector(einsum('ijk,ijkl->', E, G)))
# expect_equal(tmp74, as.vector(einsum('ijk,ijkl->i', E, G)))
# expect_equal(tmp75, as.vector(einsum('ijk,ijkl->j', E, G)))
# expect_equal(tmp76, as.vector(einsum('ijk,ijkl->k', E, G)))
# expect_equal(tmp77, as.vector(einsum('ijk,ijkl->l', E, G)))
# expect_equal(tmp78, as.array(einsum('ijk,ijkl->ij', E, G)))
# expect_equal(tmp79, as.array(einsum('ijk,ijkl->ji', E, G)))
# expect_equal(tmp80, as.array(einsum('ijk,ijkl->ik', E, G)))
# expect_equal(tmp81, as.array(einsum('ijk,ijkl->ki', E, G)))
# expect_equal(tmp82, as.array(einsum('ijk,ijkl->il', E, G)))
# expect_equal(tmp83, as.array(einsum('ijk,ijkl->li', E, G)))
# expect_equal(tmp84, as.array(einsum('ijk,ijkl->jk', E, G)))
# expect_equal(tmp85, as.array(einsum('ijk,ijkl->kj', E, G)))
# expect_equal(tmp86, as.array(einsum('ijk,ijkl->jl', E, G)))
# expect_equal(tmp87, as.array(einsum('ijk,ijkl->lj', E, G)))
# expect_equal(tmp88, as.array(einsum('ijk,ijkl->kl', E, G)))
# expect_equal(tmp89, as.array(einsum('ijk,ijkl->lk', E, G)))

# expect_equal(tmp90, as.array(einsum('ijk,ijkl->ijk', E, G)))
# expect_equal(tmp91, as.array(einsum('ijk,ijkl->ikj', E, G)))
# expect_equal(tmp92, as.array(einsum('ijk,ijkl->jik', E, G)))
# expect_equal(tmp93, as.array(einsum('ijk,ijkl->jki', E, G)))
# expect_equal(tmp94, as.array(einsum('ijk,ijkl->kij', E, G)))
# expect_equal(tmp95, as.array(einsum('ijk,ijkl->kji', E, G)))
# expect_equal(tmp96, as.array(einsum('ijk,ijkl->ijl', E, G)))
# expect_equal(tmp97, as.array(einsum('ijk,ijkl->ilj', E, G)))
# expect_equal(tmp98, as.array(einsum('ijk,ijkl->jil', E, G)))
# expect_equal(tmp99, as.array(einsum('ijk,ijkl->jli', E, G)))
# expect_equal(tmp100, as.array(einsum('ijk,ijkl->lij', E, G)))
# expect_equal(tmp101, as.array(einsum('ijk,ijkl->lji', E, G)))
# expect_equal(tmp102, as.array(einsum('ijk,ijkl->ikl', E, G)))
# expect_equal(tmp103, as.array(einsum('ijk,ijkl->ilk', E, G)))
# expect_equal(tmp104, as.array(einsum('ijk,ijkl->kil', E, G)))
# expect_equal(tmp105, as.array(einsum('ijk,ijkl->kli', E, G)))
# expect_equal(tmp106, as.array(einsum('ijk,ijkl->lik', E, G)))
# expect_equal(tmp107, as.array(einsum('ijk,ijkl->lki', E, G)))
# expect_equal(tmp108, as.array(einsum('ijk,ijkl->jkl', E, G)))
# expect_equal(tmp109, as.array(einsum('ijk,ijkl->jlk', E, G)))
# expect_equal(tmp110, as.array(einsum('ijk,ijkl->kjl', E, G)))
# expect_equal(tmp111, as.array(einsum('ijk,ijkl->klj', E, G)))
# expect_equal(tmp112, as.array(einsum('ijk,ijkl->ljk', E, G)))
# expect_equal(tmp113, as.array(einsum('ijk,ijkl->lkj', E, G)))

# context("### einsum (sum + multiply + transpose, three tensor) ###\n")
# expect_equal(tmp114, as.vector(einsum('i,ij,ijk->', A, D, F)))
# expect_equal(tmp115, as.vector(einsum('i,ij,ijk->i', A, D, F)))
# expect_equal(tmp116, as.vector(einsum('i,ij,ijk->j', A, D, F)))
# expect_equal(tmp117, as.vector(einsum('i,ij,ijk->k', A, D, F)))
# expect_equal(tmp118, as.array(einsum('i,ij,ijk->ij', A, D, F)))
# expect_equal(tmp119, as.array(einsum('i,ij,ijk->ik', A, D, F)))
# expect_equal(tmp120, as.array(einsum('i,ij,ijk->ji', A, D, F)))
# expect_equal(tmp121, as.array(einsum('i,ij,ijk->jk', A, D, F)))
# expect_equal(tmp122, as.array(einsum('i,ij,ijk->ki', A, D, F)))
# expect_equal(tmp123, as.array(einsum('i,ij,ijk->kj', A, D, F)))
# expect_equal(tmp124, as.array(einsum('i,ij,ijk->ijk', A, D, F)))

# # 激重（10分くらい？）
# # system.time(as.array(einsum('i,ij,ijk,ijkl->ijkl', A, D, F, H)))

# # # cf.
# # # https://www.procrasist.com/entry/einsum
# # # https://github.com/numpy/numpy/blob/623bc1fae1d47df24e7f1e29321d0c0ba2771ce0/numpy/typing/tests/data/pass/einsumfunc.py
# # # https://ajcr.net/Basic-guide-to-einsum/
