# einsumで表現できるもの
# multiply: 共通の添字があるところでかけ算（,の左右に同じ添字があればかける）
# sum: かけたものを足してスカラーにする（->の左から右で消えている添字は足される）
# transpose: 最後に出力する際に並び順を変更（->の右側の添字の順番に並び替え）

# np.einsumが凝っているところ: 数値以外でも使える、かける順番を最適化している?

import numpy as np

# A: ベクトル（一階テンソル）
# B: ベクトル（一階テンソル）
# C: 行列（二階テンソル）
# D: 行列（二階テンソル）
# E: 三階テンソル
# F: 四階テンソル
A = np.random.rand(3)
B = np.random.rand(3)
C = np.random.rand(3,3)
D = np.random.rand(3,4)
E = np.random.rand(3,3,3)
F = np.random.rand(3,4,5)
G = np.random.rand(3,3,3,3)
H = np.random.rand(3,4,5,6)

# transpose（「並び順を変えない = ただ中身を見るだけ」も含む）
np.einsum('i', A)
np.einsum('ij', D)
np.einsum('ijk', F)
np.einsum('ijkl', G)

np.einsum('ji', D)
np.einsum('ij->ji', D)

np.einsum('ikj', F)
np.einsum('ijk->ikj', F)
np.einsum('jik', F)
np.einsum('ijk->jik', F)
np.einsum('jki', F)
np.einsum('ijk->jki', F)
np.einsum('kij', F)
np.einsum('ijk->kij', F)
np.einsum('kji', F)
np.einsum('ijk->kji', F)

np.einsum('ijlk', G)
np.einsum('ijkl->ijlk', G)
np.einsum('ikjl', G)
np.einsum('ijkl->ikjl', G)
np.einsum('iklj', G)
np.einsum('ijkl->iklj', G)
np.einsum('iljk', G)
np.einsum('ijkl->iljk', G)
np.einsum('iljk', G)
np.einsum('ijkl->iljk', G)
np.einsum('jikl', G)
np.einsum('ijkl->jikl', G)
np.einsum('jilk', G)
np.einsum('ijkl->jilk', G)
np.einsum('jkil', G)
np.einsum('ijkl->jkil', G)
np.einsum('jkli', G)
np.einsum('ijkl->jkli', G)
np.einsum('jlik', G)
np.einsum('ijkl->jlik', G)
np.einsum('jlki', G)
np.einsum('ijkl->jlki', G)
np.einsum('kijl', G)
np.einsum('ijkl->kijl', G)
np.einsum('kilj', G)
np.einsum('ijkl->kilj', G)
np.einsum('kjil', G)
np.einsum('ijkl->kjil', G)
np.einsum('kjli', G)
np.einsum('ijkl->kjli', G)
np.einsum('klij', G)
np.einsum('ijkl->klij', G)
np.einsum('klji', G)
np.einsum('ijkl->klji', G)
np.einsum('lijk', G)
np.einsum('ijkl->lijk', G)
np.einsum('likj', G)
np.einsum('ijkl->likj', G)
np.einsum('ljik', G)
np.einsum('ijkl->ljik', G)
np.einsum('ljki', G)
np.einsum('ijkl->ljki', G)
np.einsum('lkij', G)
np.einsum('ijkl->lkij', G)
np.einsum('lkji', G)
np.einsum('ijkl->lkji', G)

# sum（colSum, rowSum, modeSumも含む）
np.einsum('i->', A)
np.einsum('ij->', D)
np.einsum('ij->i', D)
np.einsum('ij->j', D)
np.einsum('ijk->', F)
np.einsum('ijk->i', F)
np.einsum('ijk->j', F)
np.einsum('ijk->k', F)
np.einsum('ijk->ij', F)
np.einsum('ijk->jk', F)
np.einsum('ijk->ik', F)

np.einsum('ijkl->i', G)
np.einsum('ijkl->j', G)
np.einsum('ijkl->k', G)
np.einsum('ijkl->l', G)
np.einsum('ijkl->ij', G)
np.einsum('ijkl->ik', G)
np.einsum('ijkl->il', G)
np.einsum('ijkl->ji', G)
np.einsum('ijkl->jk', G)
np.einsum('ijkl->jl', G)
np.einsum('ijkl->ki', G)
np.einsum('ijkl->kj', G)
np.einsum('ijkl->kl', G)
np.einsum('ijkl->li', G)
np.einsum('ijkl->lj', G)
np.einsum('ijkl->lk', G)
np.einsum('ijkl->ijk', G)
np.einsum('ijkl->ijl', G)
np.einsum('ijkl->ikj', G)
np.einsum('ijkl->ikl', G)
np.einsum('ijkl->ilj', G)
np.einsum('ijkl->ilk', G)
np.einsum('ijkl->jik', G)
np.einsum('ijkl->jil', G)
np.einsum('ijkl->jki', G)
np.einsum('ijkl->jkl', G)
np.einsum('ijkl->jli', G)
np.einsum('ijkl->jlk', G)
np.einsum('ijkl->kij', G)
np.einsum('ijkl->kil', G)
np.einsum('ijkl->kji', G)
np.einsum('ijkl->kjl', G)
np.einsum('ijkl->kli', G)
np.einsum('ijkl->klj', G)
np.einsum('ijkl->lij', G)
np.einsum('ijkl->lik', G)
np.einsum('ijkl->lji', G)
np.einsum('ijkl->ljk', G)
np.einsum('ijkl->lki', G)
np.einsum('ijkl->lkj', G)

# multiply (対角要素取り出し)
np.einsum('ii->i', C)
np.einsum('iii->i', E)
np.einsum('iiii->i', G)

# sum + multiply（自分自身とのアダマール積）
np.einsum('i,i->i', A, A)
np.einsum('ij,ij->ij', D, D)
np.einsum('ijk,ijk->ijk', F, F)
np.einsum('ijkl,ijkl->ijkl', G, G)

# sum + multiply（自分自身=自乗和、sqrtをとればフロベニウスノルム）
np.einsum('i,i', A, A)
np.einsum('i,i->', A, A)
np.einsum('ij,ij', D, D)
np.einsum('ij,ij->', D, D)
np.einsum('ijk,ijk', F, F)
np.einsum('ijk,ijk->', F, F)
np.einsum('ijkl,ijkl', G, G)
np.einsum('ijkl,ijkl->', G, G)

# multiply + sum + transpose（異なるもの同士、アダマール積、内積、行列積、縮約積も含む）
np.einsum('ij,jk->', C, D)
np.einsum('ij,jk->i', C, D)
np.einsum('ij,jk->j', C, D)
np.einsum('ij,jk->k', C, D)
np.einsum('ij,jk->ij', C, D)
np.einsum('ij,jk->ji', C, D)
np.einsum('ij,jk->jk', C, D)
np.einsum('ij,jk->kj', C, D)
np.einsum('ij,jk->ik', C, D)
np.einsum('ij,jk->ki', C, D)

np.einsum('ij,jk->ijk', C, D)
np.einsum('ij,jk->ikj', C, D)
np.einsum('ij,jk->jik', C, D)
np.einsum('ij,jk->jki', C, D)
np.einsum('ij,jk->kij', C, D)
np.einsum('ij,jk->kji', C, D)

np.einsum('ij,ijk->', C, E)
np.einsum('ij,ijk->i', C, E)
np.einsum('ij,ijk->j', C, E)
np.einsum('ij,ijk->k', C, E)
np.einsum('ij,ijk->ij', C, E)
np.einsum('ij,ijk->ji', C, E)
np.einsum('ij,ijk->jk', C, E)
np.einsum('ij,ijk->kj', C, E)
np.einsum('ij,ijk->ik', C, E)
np.einsum('ij,ijk->ki', C, E)
np.einsum('ij,ijk->ijk', C, E)

np.einsum('ijk,ijkl->', E, G)
np.einsum('ijk,ijkl->i', E, G)
np.einsum('ijk,ijkl->j', E, G)
np.einsum('ijk,ijkl->k', E, G)
np.einsum('ijk,ijkl->l', E, G)
np.einsum('ijk,ijkl->ij', E, G)
np.einsum('ijk,ijkl->ji', E, G)
np.einsum('ijk,ijkl->ik', E, G)
np.einsum('ijk,ijkl->ki', E, G)
np.einsum('ijk,ijkl->il', E, G)
np.einsum('ijk,ijkl->li', E, G)
np.einsum('ijk,ijkl->jk', E, G)
np.einsum('ijk,ijkl->kj', E, G)
np.einsum('ijk,ijkl->jl', E, G)
np.einsum('ijk,ijkl->lj', E, G)
np.einsum('ijk,ijkl->kl', E, G)
np.einsum('ijk,ijkl->lk', E, G)

np.einsum('ijk,ijkl->ijk', E, G)
np.einsum('ijk,ijkl->ikj', E, G)
np.einsum('ijk,ijkl->jik', E, G)
np.einsum('ijk,ijkl->jki', E, G)
np.einsum('ijk,ijkl->kij', E, G)
np.einsum('ijk,ijkl->kji', E, G)
np.einsum('ijk,ijkl->ijl', E, G)
np.einsum('ijk,ijkl->ilj', E, G)
np.einsum('ijk,ijkl->jil', E, G)
np.einsum('ijk,ijkl->jli', E, G)
np.einsum('ijk,ijkl->lij', E, G)
np.einsum('ijk,ijkl->lji', E, G)
np.einsum('ijk,ijkl->ikl', E, G)
np.einsum('ijk,ijkl->ilk', E, G)
np.einsum('ijk,ijkl->kil', E, G)
np.einsum('ijk,ijkl->kli', E, G)
np.einsum('ijk,ijkl->lik', E, G)
np.einsum('ijk,ijkl->lki', E, G)

np.einsum('ijk,ijkl->jkl', E, G)
np.einsum('ijk,ijkl->jlk', E, G)
np.einsum('ijk,ijkl->kjl', E, G)
np.einsum('ijk,ijkl->klj', E, G)
np.einsum('ijk,ijkl->ljk', E, G)
np.einsum('ijk,ijkl->lkj', E, G)

# Ref
# https://ajcr.net/Basic-guide-to-einsum/